### PR TITLE
Arm building

### PR DESCRIPTION
**Pull request by jcapriot**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcapriot** [comment]
@conda-forge-admin, please rerender

**Comment by jcapriot** [comment]
@akhmerov This should be good to go on here now.

A couple notes regarding the requirements in the host and build section.
- Generally you should rely on conda-forge's global pinnings for packages that are used there: (of which they pin `numpy` and `mumps-seq`/`mumps-mpi` are part of). So essentially you need to remove the version requirements and then rerender the build scripts.
- You previouly had `numpy` in the host section as `>=1.23` which caused all of the binaries to be built against the highest available version (1.26) which can cause a ton of conflicts with other libraries. It is odd, but the version of numpy you build against doesn't have to be the same as the minimum runtime version you support. It's usually best to let conda-forge take care of this aspect. Then set the lower bound in the `pin_compatible` to ensure runtime versions.

As you might see, re-rendering it without the version requirements in the build and host sections created explicit versions for the different `numpy` version for each `python` version automatically. It also included the version of `mumps_seq` that is pinned as well.

Another note:
In order to enable cross-platform building in meson, you need to configure it first and then build, thus why there are now `bld.bat` and `build.sh`  scripts.

**Comment by jcapriot** [comment]
As a side note, we should be able to now add support for `linux_aarch64` and `linux_ppc64le` platforms as well (`mumps` is available through `conda-forge` on those too!).

**Review by akhmerov — APPROVED** [review]
Thanks for the explanation and the fix, this is really useful!

**Pull request merged**
